name: "Common operations"
description: "do something common for all test"
runs:
  using: "composite"
  steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven
    - name: download middlewares
      uses: actions/cache@v3
      with:
        path: |
          apache-zookeeper-*/
          Local-CSE-2.1.3-linux-amd64.zip
        key: ${{ runner.os }}-middlewares-${{ github.run_id }}
    - name: download agent
      uses: actions/cache@v3
      with:
        path: sermant-agent-*/
        key: ${{ runner.os }}-agent-${{ github.run_id }}
    - name: start zookeeper
      shell: bash
      run: bash apache-zookeeper-3.6.3-bin/bin/zkServer.sh start apache-zookeeper-3.6.3-bin/conf/zoo_sample.cfg
    - name: start cse
      shell: bash
      run: |
        export ROOT_PATH=$(pwd)
        bash ./sermant-integration-tests/scripts/startCse.sh
    - name: cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: plugin change check
      uses: ./.github/actions/common/plugin-change-check
